### PR TITLE
Remove unused variable warning on GCC

### PR DESCRIPTION
**Pull request by arcfide**
This should fix the final meaningful warning in GCC for namespaces that have no global variables.

### CODE REVIEW

**Comment by arcfide** [comment]
@bernecky 

This should fix the final unused variable warning for you. Can you confirm that it does? This won't fix the unused functions, but those warnings should go away as soon as you have a non-empty namespace.

**Comment by bernecky** [comment]
NFG. Domain error has returned, due to several gcc errors:

```
modu.cpp:345:53: error: reference to ‘index’ is ambiguous
modu.cpp:346:23: error: ‘ix’ was not declared in this scope; did you mean ‘id’?
modu.cpp:353:20: error: ‘ix’ was not declared in this scope; did you mean ‘id’?

```

This on gcc-warnings branch.

**Comment by arcfide** [comment]
Yes, the gcc-warnings branch is only focused on fixing the warnings, and the index-namespace branch is only focused on fixing the index errors that you were seeing which were leading to a DOMAIN ERROR, the two are mutually exclusive patches to the compiler, so you will not see the changes in one branch in the changes of the other branch.

**Comment by bernecky** [comment]
These errors appear to have away; ditto the DOMAIN ERROR.

**Pull request merged**
