### PR TITLE
Fixes for GCC Warnings

### LINKED ISSUE #431: C compiler (gcc) warnings when compiling generated code
Dyalog APL/S-64 Version 18.0.39660
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Co-dfns commit #: 0d40d117365964cc21830d59bbdf510df80b887b

A compilation of very simple code produces warnings from the C
compiler. These obscure real errors. IMO, compiles should execute
cleanly.

```
      )Clear
clear ws
        )ns ns1
#.ns1
      )cs ns1
#.ns1
      F←{⌽⍳⍵}
      F 10
9 8 7 6 5 4 3 2 1 0

      )cs
#
      ns1.F 20
19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0
      ]compile ns1 modu -af=cpu
PCG
 modu.cpp: In function ‘I DyalogGetInterpreterFunctions(dwa*)’:                                                             
 modu.cpp:111:37: warning: comparison of integer expressions of different signedness: ‘B’ {aka ‘long long int’} and ‘long un
   111 |  if(p)dwafns=p;else R 0;if(dwafns->z<sizeof(S dwa))R 16;R 0;}                                                      
       |                            ~~~~~~~~~^~~~~~~~~~~~~~                                                                 
 modu.cpp: In member function ‘virtual V iot_f::operator()(A&, const A&, const A&, ENV&)’:                                  
 modu.cpp:212:11: warning: suggest parentheses around assignment used as truth value [-Wparentheses]                        
   212 |  for(I h;h=lc/2;lc-=h){array t=z.v+h;replace(z.v,lv(t)>rv,t);}                                                     
       |          ~^~~~~                                                                                                    
 modu.cpp: In member function ‘virtual V cat_f::operator()(A&, const A&, ENV&, const A&)’:                                  
 modu.cpp:268:32: warning: unused variable ‘c’ [-Wunused-variable]                                                          
   268 |  I s=(I)axv[ac-1],ei=(I)axv[0],c=1;                                                                                
       |                                ^                                                                                   
 modu.cpp: In member function ‘virtual V cat_f::operator()(A&, const A&, const A&, ENV&, const A&)’:                        
 modu.cpp:276:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]                                     
   276 |   if(l.r)cat_c(nl,l,e,ax);if(r.r)cat_c(nr,r,e,ax);                                                                 
       |   ^~                                                                                                               
 modu.cpp:276:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’        
   276 |   if(l.r)cat_c(nl,l,e,ax);if(r.r)cat_c(nr,r,e,ax);                                                                 
       |                           ^~                                                                                       
 modu.cpp:277:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]                                     
   277 |   if(!l.r&&!r.r)cat_c(nl,l,e,ax);cat_c(nr,r,e,ax);                                                                 
       |   ^~                                                                                                               
 modu.cpp:277:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’        
   277 |   if(!l.r&&!r.r)cat_c(nl,l,e,ax);cat_c(nr,r,e,ax);                                                                 
       |                                  ^~~~~                                                                             
 modu.cpp: In member function ‘virtual V fn10_f::operator()(A&, const A&, const A&, ENV&)’:                                 
 modu.cpp:328:21: warning: comparison of integer expressions of different signedness: ‘std::vector<std::vector<BX>*>::size_t
   328 | FRM f(0);if(e.size()<=fd)e.resize(fd+1);of=e[fd];e[fd]=&f;                                                         
       |             ~~~~~~~~^~~~                                                                                           
 modu.cpp:336:18: warning: catching polymorphic type ‘class af::exception’ by value [-Wcatch-value=]                        
   336 |  catch(exception x){e[fd]=of;throw x;}}                                                                            
       |                  ^                                                                                                 
 modu.cpp: In function ‘V F_dwa(lp*, lp*, lp*)’:                                                                            
 modu.cpp:97:18: warning: catching polymorphic type ‘class af::exception’ by value [-Wcatch-value=]                         
    97 |  catch(exception e){msg=mkstr(e.what());dmx.e=msg.c_str();derr(500);}}\                                            
       |                  ^                                                                                                 
 modu.cpp:337:1: note: in expansion of macro ‘EF’                                                                           
   337 | EF(0,F,0)                                                                                                          
       | ^~                                                                                                                 
 modu.cpp: At global scope:                                                                                                 
 modu.cpp:112:5: warning: ‘V err(U, wchar_t*)’ defined but not used [-Wunused-function]                                     
   112 | Z V err(U n,wchar_t*e){dmx.e=e;throw n;}Z V err(U n){dmx.e=L"";throw n;}                                           
       |     ^~~                                                                                                            

```

### PR DESCRIPTION
**Pull request by arcfide**
Fixes #431

### CODE REVIEW

**Comment by arcfide** [comment]
@bernecky This should fix your issues with #431 . Can you please let me know if it works for you?

**Comment by bernecky** [comment]
Ah, that's better, but not quite there yet. 

  ```
    )clear
clear ws
      )cs ns1
Namespace does not exist
      )ns ns1
#.ns1
      F←{⌽⍳⍵}
      )cs 
#
      ]compile ns1 modu
PCG
 modu.cpp: In member function ‘virtual V fn0_f::operator()(A&, CA&, CA&, ENV&)’:        
 modu.cpp:220:22: warning: unused variable ‘fd’ [-Wunused-variable]                     
   220 | DF(fn0_f){if(is0)R;I fd=0;STK s;e[0]=new FRM(0);                               
       |                      ^~                                                        
 modu.cpp: At global scope:                                                             
 modu.cpp:112:5: warning: ‘V err(U, wchar_t*)’ defined but not used [-Wunused-function] 
   112 | Z V err(U n,wchar_t*e){dmx.e=e;throw n;}Z V err(U n){dmx.e=L"";throw n;}       
       |     ^~~                                                                        
 modu.cpp:109:18: warning: ‘V derr(U)’ defined but not used [-Wunused-function]         
   109 | S dwa*dwafns;Z V derr(U n){dmx.n=n;dwafns->ws->er(&dmx);}                      
       |                  ^~~~                                                   
```

**Comment by arcfide** [comment]
I'm not sure what to do about those, because I want that warning in the compiler, and with more realistic examples, those warnings will go away, but with small test examples, you're going to end up with them. I'll have to see if there is a way to address this, but I'm not sure.

**Comment by arcfide** [comment]
> Ah, that's better, but not quite there yet.
> 
> ```
>   )clear
> clear ws
>     )cs ns1
> Namespace does not exist
>     )ns ns1
> #.ns1
>     F←{⌽⍳⍵}
>     )cs 
> #
>     ]compile ns1 modu
> PCG
> modu.cpp: In member function ‘virtual V fn0_f::operator()(A&, CA&, CA&, ENV&)’:        
> modu.cpp:220:22: warning: unused variable ‘fd’ [-Wunused-variable]                     
>  220 | DF(fn0_f){if(is0)R;I fd=0;STK s;e[0]=new FRM(0);                               
>      |                      ^~                                                        
> modu.cpp: At global scope:                                                             
> modu.cpp:112:5: warning: ‘V err(U, wchar_t*)’ defined but not used [-Wunused-function] 
>  112 | Z V err(U n,wchar_t*e){dmx.e=e;throw n;}Z V err(U n){dmx.e=L"";throw n;}       
>      |     ^~~                                                                        
> modu.cpp:109:18: warning: ‘V derr(U)’ defined but not used [-Wunused-function]         
>  109 | S dwa*dwafns;Z V derr(U n){dmx.n=n;dwafns->ws->er(&dmx);}                      
>      |                  ^~~~                                                   
> ```

Just a note, but your `F...` line doesn't do anything meaningful in your test. All you did was compile an empty namespace without any data in it. I don't think it's worth it to spend more time getting rid of the unused function warnings because they should only show up when you have an empty namespace. 

I have something that I'm testing for fixing the last unused variable warning.

**Comment by bernecky** [comment]
Sorry -- too many APL windows makes Bob a bad bug reporter. Tomorrow...

**Comment by bernecky** [comment]
Perhaps ]compile should refuse to compile an empty namespace. I realize this produces the sound of a no-hand clapping
empty array joke, but I would prefer to be notified of such an attempt, as there is no way to invoke the
compiled code that would [not] be produced.

**Comment by arcfide** [comment]
Actually, compiling an empty namespace is not simply an exercise in completeness. An empty namespace provides access to the Co-dfns runtime API, regardless of what other functions might be exported, so if you, for instance, just want to use the graphing functions from Co-dfns, you could do that with just an empty namespace. So, there are many ways of invoking the compiled code even with an empty namespace. I have in fact used this a few times before and it is relatively useful.

**Pull request merged**
